2014-11-30 20:35:44,653 - [INFO] - from play in pool-21-thread-2 
Listening for HTTP on /0:0:0:0:0:0:0:0:9000

2014-11-30 20:36:05,793 - [ERROR] - from com.jolbox.bonecp.hooks.AbstractConnectionHook in play-internal-execution-context-1 
Failed to obtain initial connection Sleeping for 0ms and trying again. Attempts left: 0. Exception: java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos.Message:IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db"
IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db" [90031-175]

2014-11-30 20:36:05,804 - [ERROR] - from application in New I/O worker #1 


! @6kc5oc0b6 - Internal server error, for (GET) [/] ->

play.api.Configuration$$anon$1: Configuration error[Cannot connect to database [default]]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Configuration.reportError(Configuration.scala:743) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:247) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.map(List.scala:274) ~[scala-library-2.11.1.jar:na]
	at play.api.db.BoneCPPlugin.onStart(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.foreach(List.scala:383) ~[scala-library-2.11.1.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$.start(Play.scala:90) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:157) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.util.Success.flatMap(Try.scala:230) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db"
IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db" [90031-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.get(DbException.java:161) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.convertIOException(DbException.java:318) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:191) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:34) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FileUtils.toRealPath(FileUtils.java:79) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:393) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:41) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:160) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:139) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:122) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:28) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:323) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.Driver.connect(Driver.java:73) ~[h2-1.3.175.jar:1.3.175]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120) ~[bonecp-0.8.0.RELEASE.jar:na]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:240) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	... 26 common frames omitted
Caused by: java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos
	at java.io.WinNTFileSystem.canonicalize0(Native Method) ~[na:1.8.0_25]
	at java.io.WinNTFileSystem.canonicalize(Unknown Source) ~[na:1.8.0_25]
	at java.io.File.getCanonicalPath(Unknown Source) ~[na:1.8.0_25]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:188) ~[h2-1.3.175.jar:1.3.175]
	... 44 common frames omitted

2014-11-30 20:36:05,804 - [ERROR] - from application in New I/O worker #2 


! @6kc5oc0b6 - Internal server error, for (GET) [/] ->

play.api.Configuration$$anon$1: Configuration error[Cannot connect to database [default]]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Configuration.reportError(Configuration.scala:743) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:247) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.map(List.scala:274) ~[scala-library-2.11.1.jar:na]
	at play.api.db.BoneCPPlugin.onStart(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.foreach(List.scala:383) ~[scala-library-2.11.1.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$.start(Play.scala:90) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:157) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.util.Success.flatMap(Try.scala:230) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db"
IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db" [90031-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.get(DbException.java:161) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.convertIOException(DbException.java:318) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:191) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:34) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FileUtils.toRealPath(FileUtils.java:79) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:393) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:41) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:160) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:139) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:122) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:28) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:323) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.Driver.connect(Driver.java:73) ~[h2-1.3.175.jar:1.3.175]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120) ~[bonecp-0.8.0.RELEASE.jar:na]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:240) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	... 26 common frames omitted
Caused by: java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos
	at java.io.WinNTFileSystem.canonicalize0(Native Method) ~[na:1.8.0_25]
	at java.io.WinNTFileSystem.canonicalize(Unknown Source) ~[na:1.8.0_25]
	at java.io.File.getCanonicalPath(Unknown Source) ~[na:1.8.0_25]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:188) ~[h2-1.3.175.jar:1.3.175]
	... 44 common frames omitted

2014-11-30 20:40:09,540 - [WARN] - from play in play-internal-execution-context-1 
Error stopping plugin
java.lang.NullPointerException: null
	at play.libs.ws.ning.NingWSPlugin.onStop(NingWSPlugin.java:31) ~[play-java-ws_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$stop$1$$anonfun$apply$1$$anonfun$apply$mcV$sp$2.apply(Play.scala:108) [play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$stop$1$$anonfun$apply$1$$anonfun$apply$mcV$sp$2.apply(Play.scala:107) [play_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.foreach(List.scala:383) [scala-library-2.11.1.jar:na]
	at play.api.Play$$anonfun$stop$1$$anonfun$apply$1.apply$mcV$sp(Play.scala:107) [play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$stop$1$$anonfun$apply$1.apply(Play.scala:107) [play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$stop$1$$anonfun$apply$1.apply(Play.scala:107) [play_2.11-2.3.6.jar:2.3.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) [play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$stop$1.apply(Play.scala:106) [play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$stop$1.apply(Play.scala:105) [play_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) [scala-library-2.11.1.jar:na]
	at play.api.Play$.stop(Play.scala:105) [play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:142) [play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) [play_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) [scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) [play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) [play_2.11-2.3.6.jar:2.3.6]
	at scala.util.Success.flatMap(Try.scala:230) [scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128) [play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) [play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.1.jar:na]

2014-11-30 20:40:09,588 - [ERROR] - from com.jolbox.bonecp.hooks.AbstractConnectionHook in play-internal-execution-context-1 
Failed to obtain initial connection Sleeping for 0ms and trying again. Attempts left: 0. Exception: java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos.Message:IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db"
IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db" [90031-175]

2014-11-30 20:40:09,590 - [ERROR] - from application in New I/O worker #2 


! @6kc5opn1p - Internal server error, for (GET) [/] ->

play.api.Configuration$$anon$1: Configuration error[Cannot connect to database [default]]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Configuration.reportError(Configuration.scala:743) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:247) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.map(List.scala:274) ~[scala-library-2.11.1.jar:na]
	at play.api.db.BoneCPPlugin.onStart(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.foreach(List.scala:383) ~[scala-library-2.11.1.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$.start(Play.scala:90) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:157) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.util.Success.flatMap(Try.scala:230) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db"
IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db" [90031-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.get(DbException.java:161) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.convertIOException(DbException.java:318) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:191) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:34) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FileUtils.toRealPath(FileUtils.java:79) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:393) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:41) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:160) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:139) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:122) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:28) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:323) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.Driver.connect(Driver.java:73) ~[h2-1.3.175.jar:1.3.175]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120) ~[bonecp-0.8.0.RELEASE.jar:na]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:240) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	... 26 common frames omitted
Caused by: java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos
	at java.io.WinNTFileSystem.canonicalize0(Native Method) ~[na:1.8.0_25]
	at java.io.WinNTFileSystem.canonicalize(Unknown Source) ~[na:1.8.0_25]
	at java.io.File.getCanonicalPath(Unknown Source) ~[na:1.8.0_25]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:188) ~[h2-1.3.175.jar:1.3.175]
	... 44 common frames omitted

2014-11-30 20:40:11,006 - [ERROR] - from application in New I/O worker #2 


! @6kc5opn1p - Internal server error, for (GET) [/] ->

play.api.Configuration$$anon$1: Configuration error[Cannot connect to database [default]]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Configuration.reportError(Configuration.scala:743) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:247) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.map(List.scala:274) ~[scala-library-2.11.1.jar:na]
	at play.api.db.BoneCPPlugin.onStart(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.foreach(List.scala:383) ~[scala-library-2.11.1.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$.start(Play.scala:90) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:157) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.util.Success.flatMap(Try.scala:230) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db"
IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db" [90031-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.get(DbException.java:161) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.convertIOException(DbException.java:318) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:191) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:34) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FileUtils.toRealPath(FileUtils.java:79) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:393) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:41) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:160) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:139) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:122) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:28) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:323) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.Driver.connect(Driver.java:73) ~[h2-1.3.175.jar:1.3.175]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120) ~[bonecp-0.8.0.RELEASE.jar:na]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:240) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	... 26 common frames omitted
Caused by: java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos
	at java.io.WinNTFileSystem.canonicalize0(Native Method) ~[na:1.8.0_25]
	at java.io.WinNTFileSystem.canonicalize(Unknown Source) ~[na:1.8.0_25]
	at java.io.File.getCanonicalPath(Unknown Source) ~[na:1.8.0_25]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:188) ~[h2-1.3.175.jar:1.3.175]
	... 44 common frames omitted

2014-11-30 20:40:12,350 - [ERROR] - from application in New I/O worker #2 


! @6kc5opn1p - Internal server error, for (GET) [/] ->

play.api.Configuration$$anon$1: Configuration error[Cannot connect to database [default]]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Configuration.reportError(Configuration.scala:743) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:247) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.map(List.scala:274) ~[scala-library-2.11.1.jar:na]
	at play.api.db.BoneCPPlugin.onStart(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.foreach(List.scala:383) ~[scala-library-2.11.1.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$.start(Play.scala:90) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:157) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.util.Success.flatMap(Try.scala:230) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db"
IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db" [90031-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.get(DbException.java:161) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.convertIOException(DbException.java:318) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:191) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:34) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FileUtils.toRealPath(FileUtils.java:79) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:393) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:41) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:160) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:139) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:122) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:28) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:323) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.Driver.connect(Driver.java:73) ~[h2-1.3.175.jar:1.3.175]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120) ~[bonecp-0.8.0.RELEASE.jar:na]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:240) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	... 26 common frames omitted
Caused by: java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos
	at java.io.WinNTFileSystem.canonicalize0(Native Method) ~[na:1.8.0_25]
	at java.io.WinNTFileSystem.canonicalize(Unknown Source) ~[na:1.8.0_25]
	at java.io.File.getCanonicalPath(Unknown Source) ~[na:1.8.0_25]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:188) ~[h2-1.3.175.jar:1.3.175]
	... 44 common frames omitted

2014-11-30 20:40:13,280 - [ERROR] - from application in New I/O worker #2 


! @6kc5opn1p - Internal server error, for (GET) [/] ->

play.api.Configuration$$anon$1: Configuration error[Cannot connect to database [default]]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Configuration.reportError(Configuration.scala:743) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:247) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.map(List.scala:274) ~[scala-library-2.11.1.jar:na]
	at play.api.db.BoneCPPlugin.onStart(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.foreach(List.scala:383) ~[scala-library-2.11.1.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$.start(Play.scala:90) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:157) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.util.Success.flatMap(Try.scala:230) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db"
IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db" [90031-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.get(DbException.java:161) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.convertIOException(DbException.java:318) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:191) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:34) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FileUtils.toRealPath(FileUtils.java:79) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:393) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:41) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:160) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:139) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:122) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:28) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:323) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.Driver.connect(Driver.java:73) ~[h2-1.3.175.jar:1.3.175]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120) ~[bonecp-0.8.0.RELEASE.jar:na]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:240) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	... 26 common frames omitted
Caused by: java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos
	at java.io.WinNTFileSystem.canonicalize0(Native Method) ~[na:1.8.0_25]
	at java.io.WinNTFileSystem.canonicalize(Unknown Source) ~[na:1.8.0_25]
	at java.io.File.getCanonicalPath(Unknown Source) ~[na:1.8.0_25]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:188) ~[h2-1.3.175.jar:1.3.175]
	... 44 common frames omitted

2014-11-30 20:40:14,053 - [ERROR] - from application in New I/O worker #2 


! @6kc5opn1p - Internal server error, for (GET) [/] ->

play.api.Configuration$$anon$1: Configuration error[Cannot connect to database [default]]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Configuration.reportError(Configuration.scala:743) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:247) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.map(List.scala:274) ~[scala-library-2.11.1.jar:na]
	at play.api.db.BoneCPPlugin.onStart(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.foreach(List.scala:383) ~[scala-library-2.11.1.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$.start(Play.scala:90) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:157) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.util.Success.flatMap(Try.scala:230) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db"
IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db" [90031-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.get(DbException.java:161) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.convertIOException(DbException.java:318) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:191) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:34) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FileUtils.toRealPath(FileUtils.java:79) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:393) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:41) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:160) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:139) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:122) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:28) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:323) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.Driver.connect(Driver.java:73) ~[h2-1.3.175.jar:1.3.175]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120) ~[bonecp-0.8.0.RELEASE.jar:na]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:240) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	... 26 common frames omitted
Caused by: java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos
	at java.io.WinNTFileSystem.canonicalize0(Native Method) ~[na:1.8.0_25]
	at java.io.WinNTFileSystem.canonicalize(Unknown Source) ~[na:1.8.0_25]
	at java.io.File.getCanonicalPath(Unknown Source) ~[na:1.8.0_25]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:188) ~[h2-1.3.175.jar:1.3.175]
	... 44 common frames omitted

2014-11-30 20:40:14,626 - [ERROR] - from application in New I/O worker #2 


! @6kc5opn1p - Internal server error, for (GET) [/] ->

play.api.Configuration$$anon$1: Configuration error[Cannot connect to database [default]]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Configuration.reportError(Configuration.scala:743) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:247) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.map(List.scala:274) ~[scala-library-2.11.1.jar:na]
	at play.api.db.BoneCPPlugin.onStart(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.foreach(List.scala:383) ~[scala-library-2.11.1.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$.start(Play.scala:90) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:157) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.util.Success.flatMap(Try.scala:230) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db"
IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db" [90031-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.get(DbException.java:161) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.convertIOException(DbException.java:318) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:191) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:34) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FileUtils.toRealPath(FileUtils.java:79) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:393) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:41) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:160) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:139) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:122) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:28) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:323) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.Driver.connect(Driver.java:73) ~[h2-1.3.175.jar:1.3.175]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120) ~[bonecp-0.8.0.RELEASE.jar:na]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:240) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	... 26 common frames omitted
Caused by: java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos
	at java.io.WinNTFileSystem.canonicalize0(Native Method) ~[na:1.8.0_25]
	at java.io.WinNTFileSystem.canonicalize(Unknown Source) ~[na:1.8.0_25]
	at java.io.File.getCanonicalPath(Unknown Source) ~[na:1.8.0_25]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:188) ~[h2-1.3.175.jar:1.3.175]
	... 44 common frames omitted

2014-11-30 20:40:15,164 - [ERROR] - from application in New I/O worker #2 


! @6kc5opn1p - Internal server error, for (GET) [/] ->

play.api.Configuration$$anon$1: Configuration error[Cannot connect to database [default]]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Configuration.reportError(Configuration.scala:743) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:247) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.map(List.scala:274) ~[scala-library-2.11.1.jar:na]
	at play.api.db.BoneCPPlugin.onStart(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.foreach(List.scala:383) ~[scala-library-2.11.1.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$.start(Play.scala:90) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:157) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.util.Success.flatMap(Try.scala:230) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db"
IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db" [90031-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.get(DbException.java:161) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.convertIOException(DbException.java:318) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:191) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:34) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FileUtils.toRealPath(FileUtils.java:79) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:393) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:41) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:160) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:139) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:122) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:28) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:323) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.Driver.connect(Driver.java:73) ~[h2-1.3.175.jar:1.3.175]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120) ~[bonecp-0.8.0.RELEASE.jar:na]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:240) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	... 26 common frames omitted
Caused by: java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos
	at java.io.WinNTFileSystem.canonicalize0(Native Method) ~[na:1.8.0_25]
	at java.io.WinNTFileSystem.canonicalize(Unknown Source) ~[na:1.8.0_25]
	at java.io.File.getCanonicalPath(Unknown Source) ~[na:1.8.0_25]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:188) ~[h2-1.3.175.jar:1.3.175]
	... 44 common frames omitted

2014-11-30 20:40:15,603 - [ERROR] - from application in New I/O worker #2 


! @6kc5opn1p - Internal server error, for (GET) [/] ->

play.api.Configuration$$anon$1: Configuration error[Cannot connect to database [default]]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Configuration.reportError(Configuration.scala:743) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:247) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.map(List.scala:274) ~[scala-library-2.11.1.jar:na]
	at play.api.db.BoneCPPlugin.onStart(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.foreach(List.scala:383) ~[scala-library-2.11.1.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$.start(Play.scala:90) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:157) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.util.Success.flatMap(Try.scala:230) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db"
IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db" [90031-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.get(DbException.java:161) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.convertIOException(DbException.java:318) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:191) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:34) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FileUtils.toRealPath(FileUtils.java:79) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:393) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:41) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:160) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:139) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:122) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:28) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:323) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.Driver.connect(Driver.java:73) ~[h2-1.3.175.jar:1.3.175]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120) ~[bonecp-0.8.0.RELEASE.jar:na]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:240) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	... 26 common frames omitted
Caused by: java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos
	at java.io.WinNTFileSystem.canonicalize0(Native Method) ~[na:1.8.0_25]
	at java.io.WinNTFileSystem.canonicalize(Unknown Source) ~[na:1.8.0_25]
	at java.io.File.getCanonicalPath(Unknown Source) ~[na:1.8.0_25]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:188) ~[h2-1.3.175.jar:1.3.175]
	... 44 common frames omitted

2014-11-30 20:40:15,976 - [ERROR] - from application in New I/O worker #2 


! @6kc5opn1p - Internal server error, for (GET) [/] ->

play.api.Configuration$$anon$1: Configuration error[Cannot connect to database [default]]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Configuration.reportError(Configuration.scala:743) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:247) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.map(List.scala:274) ~[scala-library-2.11.1.jar:na]
	at play.api.db.BoneCPPlugin.onStart(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.foreach(List.scala:383) ~[scala-library-2.11.1.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$.start(Play.scala:90) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:157) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.util.Success.flatMap(Try.scala:230) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db"
IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db" [90031-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.get(DbException.java:161) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.convertIOException(DbException.java:318) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:191) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:34) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FileUtils.toRealPath(FileUtils.java:79) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:393) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:41) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:160) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:139) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:122) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:28) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:323) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.Driver.connect(Driver.java:73) ~[h2-1.3.175.jar:1.3.175]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120) ~[bonecp-0.8.0.RELEASE.jar:na]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:240) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	... 26 common frames omitted
Caused by: java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos
	at java.io.WinNTFileSystem.canonicalize0(Native Method) ~[na:1.8.0_25]
	at java.io.WinNTFileSystem.canonicalize(Unknown Source) ~[na:1.8.0_25]
	at java.io.File.getCanonicalPath(Unknown Source) ~[na:1.8.0_25]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:188) ~[h2-1.3.175.jar:1.3.175]
	... 44 common frames omitted

2014-11-30 20:40:16,521 - [ERROR] - from application in New I/O worker #2 


! @6kc5opn1p - Internal server error, for (GET) [/] ->

play.api.Configuration$$anon$1: Configuration error[Cannot connect to database [default]]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Configuration.reportError(Configuration.scala:743) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:247) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.map(List.scala:274) ~[scala-library-2.11.1.jar:na]
	at play.api.db.BoneCPPlugin.onStart(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.foreach(List.scala:383) ~[scala-library-2.11.1.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$.start(Play.scala:90) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:157) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.util.Success.flatMap(Try.scala:230) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db"
IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db" [90031-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.get(DbException.java:161) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.convertIOException(DbException.java:318) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:191) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:34) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FileUtils.toRealPath(FileUtils.java:79) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:393) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:41) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:160) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:139) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:122) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:28) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:323) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.Driver.connect(Driver.java:73) ~[h2-1.3.175.jar:1.3.175]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120) ~[bonecp-0.8.0.RELEASE.jar:na]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:240) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	... 26 common frames omitted
Caused by: java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos
	at java.io.WinNTFileSystem.canonicalize0(Native Method) ~[na:1.8.0_25]
	at java.io.WinNTFileSystem.canonicalize(Unknown Source) ~[na:1.8.0_25]
	at java.io.File.getCanonicalPath(Unknown Source) ~[na:1.8.0_25]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:188) ~[h2-1.3.175.jar:1.3.175]
	... 44 common frames omitted

2014-11-30 20:40:49,209 - [ERROR] - from application in New I/O worker #2 


! @6kc5opn1p - Internal server error, for (GET) [/] ->

play.api.Configuration$$anon$1: Configuration error[Cannot connect to database [default]]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Configuration.reportError(Configuration.scala:743) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:247) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.map(List.scala:274) ~[scala-library-2.11.1.jar:na]
	at play.api.db.BoneCPPlugin.onStart(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.foreach(List.scala:383) ~[scala-library-2.11.1.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$.start(Play.scala:90) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:157) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.util.Success.flatMap(Try.scala:230) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db"
IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db" [90031-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.get(DbException.java:161) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.convertIOException(DbException.java:318) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:191) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:34) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FileUtils.toRealPath(FileUtils.java:79) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:393) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:41) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:160) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:139) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:122) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:28) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:323) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.Driver.connect(Driver.java:73) ~[h2-1.3.175.jar:1.3.175]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120) ~[bonecp-0.8.0.RELEASE.jar:na]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:240) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	... 26 common frames omitted
Caused by: java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos
	at java.io.WinNTFileSystem.canonicalize0(Native Method) ~[na:1.8.0_25]
	at java.io.WinNTFileSystem.canonicalize(Unknown Source) ~[na:1.8.0_25]
	at java.io.File.getCanonicalPath(Unknown Source) ~[na:1.8.0_25]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:188) ~[h2-1.3.175.jar:1.3.175]
	... 44 common frames omitted

2014-11-30 20:40:50,386 - [ERROR] - from application in New I/O worker #2 


! @6kc5opn1p - Internal server error, for (GET) [/] ->

play.api.Configuration$$anon$1: Configuration error[Cannot connect to database [default]]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Configuration.reportError(Configuration.scala:743) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:247) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.map(List.scala:274) ~[scala-library-2.11.1.jar:na]
	at play.api.db.BoneCPPlugin.onStart(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.foreach(List.scala:383) ~[scala-library-2.11.1.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$.start(Play.scala:90) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:157) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.util.Success.flatMap(Try.scala:230) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db"
IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db" [90031-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.get(DbException.java:161) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.convertIOException(DbException.java:318) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:191) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:34) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FileUtils.toRealPath(FileUtils.java:79) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:393) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:41) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:160) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:139) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:122) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:28) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:323) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.Driver.connect(Driver.java:73) ~[h2-1.3.175.jar:1.3.175]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120) ~[bonecp-0.8.0.RELEASE.jar:na]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:240) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	... 26 common frames omitted
Caused by: java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos
	at java.io.WinNTFileSystem.canonicalize0(Native Method) ~[na:1.8.0_25]
	at java.io.WinNTFileSystem.canonicalize(Unknown Source) ~[na:1.8.0_25]
	at java.io.File.getCanonicalPath(Unknown Source) ~[na:1.8.0_25]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:188) ~[h2-1.3.175.jar:1.3.175]
	... 44 common frames omitted

2014-11-30 20:41:06,168 - [WARN] - from play in play-internal-execution-context-1 
Error stopping plugin
java.lang.NullPointerException: null
	at play.libs.ws.ning.NingWSPlugin.onStop(NingWSPlugin.java:31) ~[play-java-ws_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$stop$1$$anonfun$apply$1$$anonfun$apply$mcV$sp$2.apply(Play.scala:108) [play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$stop$1$$anonfun$apply$1$$anonfun$apply$mcV$sp$2.apply(Play.scala:107) [play_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.foreach(List.scala:383) [scala-library-2.11.1.jar:na]
	at play.api.Play$$anonfun$stop$1$$anonfun$apply$1.apply$mcV$sp(Play.scala:107) [play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$stop$1$$anonfun$apply$1.apply(Play.scala:107) [play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$stop$1$$anonfun$apply$1.apply(Play.scala:107) [play_2.11-2.3.6.jar:2.3.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) [play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$stop$1.apply(Play.scala:106) [play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$stop$1.apply(Play.scala:105) [play_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) [scala-library-2.11.1.jar:na]
	at play.api.Play$.stop(Play.scala:105) [play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:142) [play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) [play_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) [scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) [play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) [play_2.11-2.3.6.jar:2.3.6]
	at scala.util.Success.flatMap(Try.scala:230) [scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128) [play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) [play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.1.jar:na]

2014-11-30 20:41:06,223 - [ERROR] - from com.jolbox.bonecp.hooks.AbstractConnectionHook in play-internal-execution-context-1 
Failed to obtain initial connection Sleeping for 0ms and trying again. Attempts left: 0. Exception: java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos.Message:IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db"
IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db" [90031-175]

2014-11-30 20:41:06,229 - [ERROR] - from application in New I/O worker #2 


! @6kc5p32m9 - Internal server error, for (GET) [/] ->

play.api.Configuration$$anon$1: Configuration error[Cannot connect to database [default]]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Configuration.reportError(Configuration.scala:743) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:247) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.map(List.scala:274) ~[scala-library-2.11.1.jar:na]
	at play.api.db.BoneCPPlugin.onStart(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.foreach(List.scala:383) ~[scala-library-2.11.1.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$.start(Play.scala:90) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:157) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.util.Success.flatMap(Try.scala:230) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db"
IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db" [90031-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.get(DbException.java:161) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.convertIOException(DbException.java:318) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:191) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:34) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FileUtils.toRealPath(FileUtils.java:79) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:393) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:41) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:160) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:139) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:122) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:28) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:323) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.Driver.connect(Driver.java:73) ~[h2-1.3.175.jar:1.3.175]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120) ~[bonecp-0.8.0.RELEASE.jar:na]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:240) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	... 26 common frames omitted
Caused by: java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos
	at java.io.WinNTFileSystem.canonicalize0(Native Method) ~[na:1.8.0_25]
	at java.io.WinNTFileSystem.canonicalize(Unknown Source) ~[na:1.8.0_25]
	at java.io.File.getCanonicalPath(Unknown Source) ~[na:1.8.0_25]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:188) ~[h2-1.3.175.jar:1.3.175]
	... 44 common frames omitted

2014-11-30 20:41:06,926 - [ERROR] - from application in New I/O worker #2 


! @6kc5p32m9 - Internal server error, for (GET) [/] ->

play.api.Configuration$$anon$1: Configuration error[Cannot connect to database [default]]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Configuration.reportError(Configuration.scala:743) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:247) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.map(List.scala:274) ~[scala-library-2.11.1.jar:na]
	at play.api.db.BoneCPPlugin.onStart(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.foreach(List.scala:383) ~[scala-library-2.11.1.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$.start(Play.scala:90) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:157) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.util.Success.flatMap(Try.scala:230) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db"
IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db" [90031-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.get(DbException.java:161) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.convertIOException(DbException.java:318) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:191) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:34) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FileUtils.toRealPath(FileUtils.java:79) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:393) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:41) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:160) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:139) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:122) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:28) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:323) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.Driver.connect(Driver.java:73) ~[h2-1.3.175.jar:1.3.175]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120) ~[bonecp-0.8.0.RELEASE.jar:na]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:240) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	... 26 common frames omitted
Caused by: java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos
	at java.io.WinNTFileSystem.canonicalize0(Native Method) ~[na:1.8.0_25]
	at java.io.WinNTFileSystem.canonicalize(Unknown Source) ~[na:1.8.0_25]
	at java.io.File.getCanonicalPath(Unknown Source) ~[na:1.8.0_25]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:188) ~[h2-1.3.175.jar:1.3.175]
	... 44 common frames omitted

2014-11-30 20:41:07,512 - [ERROR] - from application in New I/O worker #2 


! @6kc5p32m9 - Internal server error, for (GET) [/] ->

play.api.Configuration$$anon$1: Configuration error[Cannot connect to database [default]]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Configuration.reportError(Configuration.scala:743) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:247) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.map(List.scala:274) ~[scala-library-2.11.1.jar:na]
	at play.api.db.BoneCPPlugin.onStart(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.foreach(List.scala:383) ~[scala-library-2.11.1.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$.start(Play.scala:90) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:157) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.util.Success.flatMap(Try.scala:230) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db"
IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db" [90031-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.get(DbException.java:161) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.convertIOException(DbException.java:318) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:191) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:34) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FileUtils.toRealPath(FileUtils.java:79) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:393) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:41) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:160) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:139) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:122) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:28) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:323) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.Driver.connect(Driver.java:73) ~[h2-1.3.175.jar:1.3.175]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120) ~[bonecp-0.8.0.RELEASE.jar:na]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:240) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	... 26 common frames omitted
Caused by: java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos
	at java.io.WinNTFileSystem.canonicalize0(Native Method) ~[na:1.8.0_25]
	at java.io.WinNTFileSystem.canonicalize(Unknown Source) ~[na:1.8.0_25]
	at java.io.File.getCanonicalPath(Unknown Source) ~[na:1.8.0_25]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:188) ~[h2-1.3.175.jar:1.3.175]
	... 44 common frames omitted

2014-11-30 20:41:07,952 - [ERROR] - from application in New I/O worker #2 


! @6kc5p32m9 - Internal server error, for (GET) [/] ->

play.api.Configuration$$anon$1: Configuration error[Cannot connect to database [default]]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Configuration.reportError(Configuration.scala:743) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:247) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.map(List.scala:274) ~[scala-library-2.11.1.jar:na]
	at play.api.db.BoneCPPlugin.onStart(DB.scala:238) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.foreach(List.scala:383) ~[scala-library-2.11.1.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$.start(Play.scala:90) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:157) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.util.Success.flatMap(Try.scala:230) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]
Caused by: org.h2.jdbc.JdbcSQLException: IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db"
IO Exception: "java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos"; "fs:play.mv.db" [90031-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.get(DbException.java:161) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.message.DbException.convertIOException(DbException.java:318) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:191) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:34) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.store.fs.FileUtils.toRealPath(FileUtils.java:79) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.ConnectionInfo.getName(ConnectionInfo.java:393) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:41) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.openSession(Engine.java:160) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:139) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:122) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.Engine.createSession(Engine.java:28) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:323) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:105) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:90) ~[h2-1.3.175.jar:1.3.175]
	at org.h2.Driver.connect(Driver.java:73) ~[h2-1.3.175.jar:1.3.175]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[na:1.8.0_25]
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416) ~[bonecp-0.8.0.RELEASE.jar:na]
	at com.jolbox.bonecp.BoneCPDataSource.getConnection(BoneCPDataSource.java:120) ~[bonecp-0.8.0.RELEASE.jar:na]
	at play.api.db.BoneCPPlugin$$anonfun$onStart$1.apply(DB.scala:240) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	... 26 common frames omitted
Caused by: java.io.IOException: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos
	at java.io.WinNTFileSystem.canonicalize0(Native Method) ~[na:1.8.0_25]
	at java.io.WinNTFileSystem.canonicalize(Unknown Source) ~[na:1.8.0_25]
	at java.io.File.getCanonicalPath(Unknown Source) ~[na:1.8.0_25]
	at org.h2.store.fs.FilePathDisk.toRealPath(FilePathDisk.java:188) ~[h2-1.3.175.jar:1.3.175]
	... 44 common frames omitted

2014-11-30 20:41:45,353 - [WARN] - from play in play-internal-execution-context-1 
Error stopping plugin
java.lang.NullPointerException: null
	at play.libs.ws.ning.NingWSPlugin.onStop(NingWSPlugin.java:31) ~[play-java-ws_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$stop$1$$anonfun$apply$1$$anonfun$apply$mcV$sp$2.apply(Play.scala:108) [play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$stop$1$$anonfun$apply$1$$anonfun$apply$mcV$sp$2.apply(Play.scala:107) [play_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.foreach(List.scala:383) [scala-library-2.11.1.jar:na]
	at play.api.Play$$anonfun$stop$1$$anonfun$apply$1.apply$mcV$sp(Play.scala:107) [play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$stop$1$$anonfun$apply$1.apply(Play.scala:107) [play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$stop$1$$anonfun$apply$1.apply(Play.scala:107) [play_2.11-2.3.6.jar:2.3.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) [play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$stop$1.apply(Play.scala:106) [play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$stop$1.apply(Play.scala:105) [play_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) [scala-library-2.11.1.jar:na]
	at play.api.Play$.stop(Play.scala:105) [play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:142) [play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) [play_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) [scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) [play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) [play_2.11-2.3.6.jar:2.3.6]
	at scala.util.Success.flatMap(Try.scala:230) [scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128) [play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) [play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.1.jar:na]

2014-11-30 20:41:45,445 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:h2:mem:play

2014-11-30 20:41:45,695 - [ERROR] - from application in New I/O worker #2 


! @6kc5p5967 - Internal server error, for (GET) [/] ->

play.api.Configuration$$anon$1: Configuration error[Configuration error[]]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Configuration.reportError(Configuration.scala:743) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.Configuration.reportError(Configuration.java:310) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:56) ~[play-java-ebean_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.foreach(List.scala:383) ~[scala-library-2.11.1.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$.start(Play.scala:90) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:157) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.util.Success.flatMap(Try.scala:230) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]
Caused by: play.api.Configuration$$anon$1: Configuration error[]
	at play.api.Configuration$.play$api$Configuration$$configError(Configuration.scala:94) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.Configuration.reportError(Configuration.scala:743) ~[play_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPApi.play$api$db$BoneCPApi$$error(DB.scala:271) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPApi$$anonfun$getDataSource$3.apply(DB.scala:437) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.db.BoneCPApi$$anonfun$getDataSource$3.apply(DB.scala:437) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at scala.Option.getOrElse(Option.scala:120) ~[scala-library-2.11.1.jar:na]
	at play.api.db.BoneCPApi.getDataSource(DB.scala:437) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.db.DB$$anonfun$getDataSource$1.apply(DB.scala:142) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.db.DB$$anonfun$getDataSource$1.apply(DB.scala:142) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.api.db.DB$.getDataSource(DB.scala:142) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.api.db.DB.getDataSource(DB.scala) ~[play-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.db.DB.getDataSource(DB.java:25) ~[play-java-jdbc_2.11-2.3.6.jar:2.3.6]
	at play.db.ebean.EbeanPlugin.onStart(EbeanPlugin.java:54) ~[play-java-ebean_2.11-2.3.6.jar:2.3.6]
	... 23 common frames omitted

2014-11-30 20:42:01,006 - [WARN] - from play in play-internal-execution-context-1 
Error stopping plugin
java.lang.NullPointerException: null
	at play.libs.ws.ning.NingWSPlugin.onStop(NingWSPlugin.java:31) ~[play-java-ws_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$stop$1$$anonfun$apply$1$$anonfun$apply$mcV$sp$2.apply(Play.scala:108) [play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$stop$1$$anonfun$apply$1$$anonfun$apply$mcV$sp$2.apply(Play.scala:107) [play_2.11-2.3.6.jar:2.3.6]
	at scala.collection.immutable.List.foreach(List.scala:383) [scala-library-2.11.1.jar:na]
	at play.api.Play$$anonfun$stop$1$$anonfun$apply$1.apply$mcV$sp(Play.scala:107) [play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$stop$1$$anonfun$apply$1.apply(Play.scala:107) [play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$stop$1$$anonfun$apply$1.apply(Play.scala:107) [play_2.11-2.3.6.jar:2.3.6]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) [play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$stop$1.apply(Play.scala:106) [play_2.11-2.3.6.jar:2.3.6]
	at play.api.Play$$anonfun$stop$1.apply(Play.scala:105) [play_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) [scala-library-2.11.1.jar:na]
	at play.api.Play$.stop(Play.scala:105) [play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:142) [play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) [play_2.11-2.3.6.jar:2.3.6]
	at scala.Option.map(Option.scala:145) [scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) [play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) [play_2.11-2.3.6.jar:2.3.6]
	at scala.util.Success.flatMap(Try.scala:230) [scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128) [play_2.11-2.3.6.jar:2.3.6]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) [play_2.11-2.3.6.jar:2.3.6]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) [scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) [scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) [scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.1.jar:na]

2014-11-30 20:42:01,076 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:h2:mem:play

2014-11-30 20:42:01,190 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

2014-11-30 20:49:49,788 - [INFO] - from play in play-internal-execution-context-1 
database [default] connected at jdbc:h2:playdb

2014-11-30 20:49:49,828 - [INFO] - from play in play-internal-execution-context-1 
Application started (Dev)

